# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Presto's Choice
email: me@prestonhunt.com
description: > # this means to ignore newlines until "baseurl:"
  Presto's Choice is a curated list of recommended products. The Presto's
  Choice for any given product represents the optimal tradeoff between 
  quality, functionality, and price.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prestoschoice.com" # the base hostname & protocol for your site
twitter_username: presto8
#github_username:  presto8

# Build settings
markdown: kramdown

comments: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

